name: CI

on:
  push:
  pull_request:

jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.8"
          - "3.9"
              
          - "3.10"
          - "3.11"
          - "3.12-dev"
          - "pypy-3.8"
          - "pypy-3.9"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

          
      - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pytest pytest-cov
              pip install mcpi
              python -m pip install Ipython --user
              python -m pip install -q -U google-generativeai
              python3 -m pip install Ipython --no-cache-dir

          
      - name: Run tests and generate coverage report
            run: |
              pytest --cov=MyAdventures --cov-report=xml tests/test_insultBot.py
              pytest --cov=MyAdventures --cov-report=xml tests/test_TNTBot.py

          
